services:
  user-service-db:
    image: redis:alpine
    volumes:
      - auth-data:/data
    ports:
      - 6379:6379
    networks:
      - user-service-network

  user-service:
    build: user-service
    ports:
      - 5000:5000
    depends_on:
      - user-service-db
      - post-service
      - stat-kafka
    networks:
      - user-service-network
      - services-network

  post-service-db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=228322
    networks:
      - post-service-network
    volumes:
      - post-data:/var/lib/postgresql/data

  post-service-adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - post-service-network

  post-service:
    build: post-service
    ports:
      - 50051:50051
    depends_on:
      - post-service-db
    networks:
      - post-service-network
      - services-network

  stat-kafka:
    image: bitnami/kafka
    ports:
      - 9092:9092
    environment:
      #- KAFKA_ADVERTISED_HOST_NAME=kafka
      #- KAFKA_ADVERTISED_PORT=9092
      - KAFKA_CREATE_TOPICS=events:1:1
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@stat-kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - stat-service-network
      - user-service-network

  stat-service-db:
    image: yandex/clickhouse-server
    #environment:
      #- CLICKHOUSE_DB=default
      #- CLICKHOUSE_USER=default
      #- ALLOW_EMPTY_PASSWORD=yes
    #expose:
    #  - 9000
    ports:
      - 8123:8123
    volumes:
      - ./stat-service/init.sql:/docker-entrypoint-initdb.d/init.sql
      - stat-data:/var/lib/clickhouse
    networks:
      - stat-service-network

  stat-service:
    build: stat-service
    ports:
      - 5001:5000
    depends_on:
      - stat-service-db
      - stat-kafka
    networks:
      - stat-service-network
      - services-network

networks:
  user-service-network:
    driver: bridge

  post-service-network:
    driver: bridge

  stat-service-network:
    driver: bridge

  services-network:
    driver: bridge

volumes:
  auth-data:
    driver: local

  post-data:
    driver: local

  stat-data:
    driver: local
